### ISSUE TITLE
Video too big on moblie

### ISSUE THREAD

**Issue by Chris5613** [Chris5613/RankRiddler#74]
The video currently on phone screens is too wide and should be fitted to make it look better.

Just a quick CSS fix most likely. 

![1c680332cdf619488c6beba72c10a133](https://github.com/Chris5613/RankRiddler/assets/24240227/145675b2-ab44-4ffb-a098-89de66609b68)

This is what it currently looks like. 

```css

.video {
  min-width: 700px;
  min-height: 300px;
  z-index: 1;
}

.youtube-wrapper {
  display: flex;
  justify-content: center;
}

@media screen and (max-width: 768px) {
  .video {
    z-index: 1;
    width: 70%;
    height: 100%;
    left: 0%;
  }
}

```

The current CSS.
